### Learning Numpy 

In [6]:
import numpy as np

a = np.matrix([1,2,1]).T

print("a: \n" + str(a))

b = np.matrix([2,2,1]).T

print("b: \n" + str(b))

A = np.matrix([[1,2],[2,1],[1,1]])
A1 = np.matrix([[1,2,1],[2,1,1]]).T

print("A: \n" + str(A))
print("A1: \n" + str(A1))

B = np.matrix([[2,1],[1,2]])
print("B: \n" + str(B))
C = np.matrix([[1,3],[0,1]])
print("C: \n" + str(C))

a: 
[[1]
 [2]
 [1]]
b: 
[[2]
 [2]
 [1]]
A: 
[[1 2]
 [2 1]
 [1 1]]
A1: 
[[1 2]
 [2 1]
 [1 1]]
B: 
[[2 1]
 [1 2]]
C: 
[[1 3]
 [0 1]]


In [7]:
res1 = a.T*b
print("a.T*b\n" + str(a.T*b))
print("a*b.T\n" + str(a*b.T))
print("A*C\n" + str(A*C))
print("C*A.T\n" + str(C*A.T))

a.T*b
[[7]]
a*b.T
[[2 2 1]
 [4 4 2]
 [2 2 1]]
A*C
[[1 5]
 [2 7]
 [1 4]]
C*A.T
[[7 5 4]
 [2 1 1]]


In [61]:
import numpy.linalg

print(str(numpy.linalg.inv(B)))

[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


In [62]:
print(str(np.array_equal(numpy.linalg.inv(B)*B, B*numpy.linalg.inv(B))))
print(str(np.array_equal(np.identity(2),B*numpy.linalg.inv(B))))

True
True


In [63]:
M = np.eye(3)
np.random.shuffle(M)
M = np.matrix(M)
print(str(M))

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


In [64]:
print(str(np.eye(3)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [65]:
print(str(np.all(M*M.T == np.eye(3))));

True


In [66]:
print(str(np.all(M.T*M == np.eye(3))))

True


In [67]:
print(str(np.array_equal(M.T, numpy.linalg.inv(M))))

True


In [69]:
np.all(M*M.T == np.eye(3))

True